### PR TITLE
Bugfix

### PR DESCRIPTION
**Pull request by zenihex**
fix `not hidden` to `hidden is not true`

### CODE REVIEW

**Comment by zenihex** [comment]
I got this warning when the changes as in #54. 
```
WARN  llowedValuesDBListQueryBuilder - Failed to evaluate the Velocity code from the query [select doc.fullName from XWikiDocument doc, BaseObject obj where obj.name = doc.fullName and obj.className = 'Blog.BlogClass' and doc.fullName<>'Blog.BlogTemplate' #if(($xwiki.getUserPreference('displayHiddenDocuments') == 0) || ("$!services.user.properties" != '' && !$services.user.properties.displayHiddenDocuments())) and not doc.hidden #end]. Root cause is [NullPointerException: The name of the Velocity template must not be null]. Continuing with the raw query. 
```

`not doc.hidden` is not valid syntax, the fix proposed here is `doc.hidden is not true`

**Comment by tmortagne** [comment]
Hi @zenihex, would be great if you could create an issue about this on https://jira.xwiki.org/browse/BLOG to associate the commit with it. We are trying to [have a jira issue for everything functional change](https://dev.xwiki.org/xwiki/bin/view/Community/DevelopmentPractices#HRule:AlwaysputaJIRAissuereferenceincommitmessages), in the case of contrib extension it's also traditionally used to produce the release note.

**Comment by zenihex** [comment]
Thank you @tmortagne . I created this ticket: https://jira.xwiki.org/browse/BLOG-212

**Comment by zenihex** [comment]
sorry about the confusion. Just in case if the change in #54 is causing any errors, the proposed fix in the PR. I don't have a good way to test the changes in a real xwiki instance. Any help is appreciated. Thanks.

**Comment by tmortagne** [comment]
> I don't have a good way to test the changes in a real xwiki instance.

The easiest is probably to download the [Standard Flavor Pre-installed demo package](https://www.xwiki.org/xwiki/bin/view/Download/DownloadVersion/?projectVersion=14.10.20) and install the blog in it.

**Pull request merged**
